[project]
name = "cmd-tool"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "flet>=0.86.5",
    "pyyaml>=6.0.3",
    "ruamel-yaml>=0.19.1",
]

[tool.flet.flutter.pubspec.dependency_overrides]
jni_flutter = "1.0.2"